### ISSUE TITLE
[Question] Does graphql-java-servlet support gzip compression?

### ISSUE THREAD

**Issue by justinnichols** [graphql-java/graphql-java-servlet#81]
I need to know if graphql-java-servlet allows for gzip compression (`Accept-Encoding: gzip` and `Content-Encoding: gzip`) and if so, is it enabled by default or is there a way to enable it?  I'm using the graphql-spring-boot starter as well.

**Comment by oliemansm** [comment]
@justinnichols Sorry for the late response. Since you're using **graphql-spring-booter-starter** as well, you can simply configure that through the Springs own application settings:
```yaml
server:
  compression:
    enabled: true
    mime-types: application/json
```
